// AUTO-GENERATED by scripts/extract-legacy-pages.js — <footer> markup shared by default.html, space-booking.html, response.html, response-newsletter.html. Do not hand-edit.
export const html = `<footer>
<div class="footer-section">
	
<div class="container-xxl">
    <div class="row">
		<div class="col-xl-6 col-lg-6 col-md-6 col-12 mb-3">
			<div class="row">
				<div class="col-xl-5 col-lg-6 col-md-6 col-sm-6 col-12 pe-xl-5 pe-lg-4 pe-md-3">
					<div class="footer-logo-bottom">Wellness India Expo</div>
					<div class="footer-logo-bottom-txt">06-08 May, 2027 <br> Bharat Mandapam, New Delhi</div>
					<div class="footer-bottom-btn-main">
						<ul>
							
							<li><a href="/space-booking" class="d-flex justify-content-between"><span>Exhibitor Enquiry </span> <i class="far fa-arrow-right btn-arrow-icon"></i></a></li>
							<li><a href="/space-booking" class="d-flex justify-content-between"><span>Partnership Enquiry </span> <i class="far fa-arrow-right btn-arrow-icon"></i></a></li>
						</ul>
					</div>
				</div>
					
				
				<div class="col-xl-7 col-lg-6 col-md-6 col-sm-6 col-12 offset-xl--2 offset-lg--1 footer-left-border ps-xl-5 ps-lg-4 ps-md-3">
					<div class="footer-bottom-heading">Let's Connect</div>
					<div class="footer-bottom-link">
						<ul>
							<li>
								<strong>Sales & Sponsorship</strong><br>
								<a href="mailto:sales@wellnessindiaexpo.com">sales@<wbr>wellnessindiaexpo.com</a>
							</li>
							<li>
								<strong>Conference & Speaker</strong><br>
								<a href="mailto:conferences@wellnessindiaexpo.com">conferences@<wbr>wellnessindiaexpo.com</a>
							</li>
							<li>
								<strong>Visitor & Delegate</strong><br>
								<a href="mailto:connect@wellnessindiaexpo.com">connect@<wbr>wellnessindiaexpo.com</a>
							</li>
							<li>
								<strong>Media & Marketing</strong><br>
								<a href="mailto:media@wellnessindiaexpo.com">media@<wbr>wellnessindiaexpo.com</a>
							</li>
						</ul>
					</div>
				</div>
				
			</div>
		</div>
		
		<div class="col-xl-6 col-lg-6 col-md-6 col-12 footer-left-border">
			<div class="row justify-content-center">
				<div class="col-12">
					<div class="footer-logo-heading">Sign up for our newsletter</div>
					<div class="footer-logo-box">
<form method="GET" action="/response-newsletter" class="newsletter-form" id="newsletterForm">
	<input type="email" name="EMAIL" id="email" placeholder="Enter Your email address" class="form-control" required>
	<button type="submit" class="button">Register</button>
<div id="newsletterFormMsg" class="form-text" style="position:absolute;left:0;top:100%;margin-top:8px;width:100%;"></div>
</form>
					</div>
				</div>
				
			</div>
			<hr class="m-4">
			<div class="row">
				<div class="col-12">
					<div class="footer-logo-heading">Organisers</div>
				</div>
			</div>
			<div class="row justify-content-center">
				<div class="col-lg-4 col-md-5 col-sm-6 col-6">
					<div class="footer-logo-box"><img src="/images/footer-event-organiger-2026-1.png" alt="Exhibitions India"></div>
				</div>
			</div>
		</div>
    </div>

</div>
</div>

<div class="footer-section-bottom">
	<div class="container-xxl">
		<div class="row">
		<div class="col-12">
			<div class="footer-copyright">Copyright © 2026 All rights reserved. Exhibitions India Group.</div>
		</div>
		</div>
	</div>
</div>

</footer>`;
